### ISSUE TITLE
Does the project support the standard UBUS?

### ISSUE THREAD

**Issue by darcyg** [mkschreder/jucid#1]
hi Martin:
Does this project support the openwrt version of UBUS?
Openwrt-feed/jucid/Makefile is used in the libubus2, do not know whether the libubus2 and libubus compatible. Does my UBUS module need to be re compiled?

thanks

**Comment by mkschreder** [comment]
Yes ubus is supported. However backend objects will no longer be forced to
be on ubus. They can be put there as well, but that will not be a mandatory
thing. So instead of the request path  being "client -> uhttpd -> ubus ->
ubus-scriptd -> bash -> lua -> ubus-scriptd -> ubus -> uhttpd -> client"
it's now going to be "client -> jucid -> lua -> jucid -> client". You will
notice a clear difference in speed.
