### ISSUE TITLE
Q: Some number.

### ISSUE THREAD

**Issue by thesabbir** [mkschreder/jucid#3]
It would be very helpful to know:
- Disk space usage.
- Memory usage.
- Cpu usage

Thanks

**Comment by mkschreder** [comment]
If I give you figures, they will never be exact because it is a modular
system and such figures depend entirely on how many modules you use and how
many new ones you have to add for your specific application. Ok 160k flash
is enough I would say, but what does this mean exactly? It is only backend
application without frontend. Is your theme using images? -- add another
5M.

If you are just looking for a plug and play system then go look somewhere
else because companies who are serious about building firmwares out of open
source components usually add many custom modifications and fixes
themselves - and then memory usage is not a meaningful question because if
something doesn't fit they either modify it themselves, suggest an
improvement or remove it entirely.

**Comment by thesabbir** [comment]
Thanks.
This is a really good work.

Actually, I am thinking of building an open source mobile app with this this backend in my spare times.
I am thinking of going with this instead of openwrt's own json rpc api. I am going to be focused on app so I wanted to make sure :)

**Comment by mkschreder** [comment]
Mobile app use is indeed one of the main goals of this backend. You can in
fact use phonegap to pack juci into a mobile app with very little effort,
but because the juci frontend is not designed for a full screen web view,
there will be many accessibility issues. However the code in the main juci
repo is a good reference of how to go about making it work.

**Comment by thesabbir** [comment]
I'm exploring juci now, you did a very good job 👍 .
I'll go with react native for app.

Thanks.
