### ISSUE TITLE
remove of lua plugin

### ISSUE THREAD

**Issue by congallenwang** [mkschreder/jucid#7]
hi,

why most of the lua scripts removed from plugin folder? you have new idea to implement these plugin?

br
Allen

**Comment by mkschreder** [comment]
I moved them back to juci instead (https://github.com/mkschreder/juci) -
because technically they belong there. We can develop a separate interface
for orange later. For example you could have scripts under /progs/ expose
json interfaces to linux cli tools etc. You can still find the scripts in
juci repo under plugins/**/rpc. If you want, you can move some of them
back.
